# Generated by Django 5.1.3 on 2025-01-28 03:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='sku',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
