# Generated by Django 5.2.5 on 2026-01-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='tag',
            field=models.CharField(blank=True, choices=[('sketch', 'Sketch'), ('flat', 'Flat'), ('shaded', 'Shaded'), ('drawing', 'Drawing'), ('painting', 'Painting'), ('oil', 'Oil'), ('cd', 'CD'), ('pins', 'Pins'), ('misc', 'Miscellaneous')], max_length=20),
        ),
    ]
